#!/usr/bin/env -S deno run --allow-read --allow-write
/**
 * elf_map_merge.ts — unifies elf-map + plan98-map into one filterable graph
 *
 * Reads private/elf-map/graph.json and private/plan98-map/graph.json (both
 * generated by elf_map.ts), tags every node with a source facet, namespaces
 * ids to dodge the 67 tag names both repos happen to share (bulletin-board,
 * cdn-video, hypertext-*, ...), and computes the rest of what's cheaply
 * inferable per node for checkbox-style faceted filtering:
 *
 *   source     'plan1' | 'plan98'
 *   kind       'elf' | 'saga'          (already on the source graphs)
 *   edgeTypes  which relationship types this node touches at all —
 *              imports / embeds / saga-embeds / renders
 *   degree     'isolated' | 'low' | 'medium' | 'high' — bucketed in+out edge count
 *   prefix     naming-convention family, first token before a '-' (or the
 *              whole tag if there's no '-') — e.g. plan98-modal -> 'plan98',
 *              hypertext-address -> 'hypertext'. cheap proxy for "does this
 *              codebase cluster around shared naming families."
 *   path              file path relative to that repo's client/public/
 *   lineCount(Bucket) tiny/small/medium/large — genuine size signal
 *   hasStyle          defines its own $.style(...) CSS
 *   externalImports   npm packages / aliased imports / non-elf relative
 *                      imports this file pulls in — not an elf-to-elf edge,
 *                      but the most interesting biometric for a human-vs-AI
 *                      comparison: what tech each side actually reaches for
 *
 * Usage:
 *   deno run ... elf_map_merge.ts
 *
 * Output:
 *   private/elf-map/combined.json
 */
import { join } from 'jsr:@std/path'

const root = new URL('../', import.meta.url).pathname
const elfMapPath = join(root, 'private', 'elf-map', 'graph.json')
const plan98Path = join(root, 'private', 'plan98-map', 'graph.json')
const outPath = join(root, 'private', 'elf-map', 'combined.json')

type SourceNode = {
  id: string, kind: string, path?: string, lineCount?: number,
  hasStyle?: boolean, externalImports?: string[],
}
type SourceGraph = { nodes: SourceNode[], edges: { from: string, to: string, type: string }[] }
type MergedNode = {
  id: string, tag: string, source: string, kind: string,
  edgeTypes: string[], degree: number, degreeBucket: string, prefix: string,
  path: string, lineCount: number, lineCountBucket: string, hasStyle: boolean, externalImports: string[],
}
type MergedEdge = { from: string, to: string, type: string }

function prefixOf(tag: string) {
  const i = tag.indexOf('-')
  return i === -1 ? tag : tag.slice(0, i)
}

function degreeBucket(n: number) {
  if (n === 0) return 'isolated'
  if (n <= 3) return 'low'
  if (n <= 10) return 'medium'
  return 'high'
}

function lineCountBucket(n: number) {
  if (n <= 30) return 'tiny'
  if (n <= 100) return 'small'
  if (n <= 300) return 'medium'
  return 'large'
}

async function loadGraph(path: string): Promise<SourceGraph | null> {
  try { return JSON.parse(await Deno.readTextFile(path)) } catch { return null }
}

const sources: [string, SourceGraph | null][] = [
  ['plan1', await loadGraph(elfMapPath)],
  ['plan98', await loadGraph(plan98Path)],
]

const nodes: Record<string, MergedNode> = {}
const edges: MergedEdge[] = []
const edgeKey = (e: MergedEdge) => `${e.from} ${e.to} ${e.type}`
const seenEdges = new Set<string>()

for (const [source, graph] of sources) {
  if (!graph) { console.log(`skip ${source} — graph.json not found, run ./plan1.sh elf-map / plan98-map first`); continue }

  const idFor = (tag: string) => `${source}:${tag}`
  const degreeCount: Record<string, number> = {}
  const edgeTypesByTag: Record<string, Set<string>> = {}

  for (const e of graph.edges) {
    degreeCount[e.from] = (degreeCount[e.from] || 0) + 1
    degreeCount[e.to] = (degreeCount[e.to] || 0) + 1
    ;(edgeTypesByTag[e.from] ??= new Set()).add(e.type)
    ;(edgeTypesByTag[e.to] ??= new Set()).add(e.type)
  }

  for (const n of graph.nodes) {
    const degree = degreeCount[n.id] || 0
    const lineCount = n.lineCount ?? 0
    nodes[idFor(n.id)] = {
      id: idFor(n.id),
      tag: n.id,
      source,
      kind: n.kind,
      edgeTypes: [...(edgeTypesByTag[n.id] || [])].sort(),
      degree,
      degreeBucket: degreeBucket(degree),
      prefix: prefixOf(n.id),
      path: n.path ?? n.id,
      lineCount,
      lineCountBucket: lineCountBucket(lineCount),
      hasStyle: n.hasStyle ?? false,
      externalImports: n.externalImports ?? [],
    }
  }

  for (const e of graph.edges) {
    const edge = { from: idFor(e.from), to: idFor(e.to), type: e.type }
    const k = edgeKey(edge)
    if (seenEdges.has(k)) continue
    seenEdges.add(k)
    edges.push(edge)
  }
}

const nodeList = Object.values(nodes)
const combined = {
  generatedAt: new Date().toISOString(),
  note: 'merged from private/elf-map/graph.json + private/plan98-map/graph.json, namespaced by source to dodge shared tag names between the two repos',
  nodes: nodeList,
  edges,
}

await Deno.writeTextFile(outPath, JSON.stringify(combined, null, 2))
console.log(`${nodeList.length} nodes, ${edges.length} edges (${sources.filter(([, g]) => g).length}/${sources.length} sources) → ${outPath}`)
